### ISSUE TITLE
Service Http which can get all drivers if they are available or busy.

### ISSUE THREAD

**Issue by papachan** [juniorgerdet/tappsi_test#1]
It would be cool gettin a params checkin all drivers available or busy

As i understand your code, i just see available drivers in your select.

``` python
drivers=Driver.objects.filter(busy=0)
```

**Comment by juniorgerdet** [comment]
fixed #1 even you can get all taxi drivers, without parameters "/api/v1/taxidrivers/" or get busy taxi drivers "api/v1/taxidrivers/?busy=1," also get just the availables api/v1/taxidrivers/?busy=0
